service: trabalho
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  
custom:
  nomeBucket: 'Trabalho'

functions:
  s3-trigger:
    handler: s3.handler
    events:
      - s3:
          bucket: ${self:custom.nomeBucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .json