service: trabalho
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: 'us-east-1'
  memorySize: 128
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
  
custom:
  nomeBucket: 'trabalho-final'

functions:
  s3-trigger:
    handler: s3.handler
    events:
      - s3:
          bucket: ${self:custom.nomeBucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .json